import type { JobApplication } from '@/types';

export const mockJobs: JobApplication[] = [
  {
    no: '1',
    company: 'Stripe',
    roleTitle: 'Frontend Engineer',
    contract: 'Full Time',
    jobLink: 'https://stripe.com/jobs',
    applicationDate: '03/01/25',
    response: 'Interview',
    interviewStage: '2nd Round',
    interviewDetails: '20/01/25 14:00 - Jamie Lee (Engineering Manager)',
    offer: '',
    notes: 'Great culture fit. Strong emphasis on React and TypeScript.',
  },
  {
    no: '2',
    company: 'Figma',
    roleTitle: 'Software Engineer Intern',
    contract: 'Intern',
    jobLink: 'https://figma.com/careers',
    applicationDate: '05/01/25',
    response: 'Offer',
    interviewStage: 'Completed',
    interviewDetails: '15/01/25 10:00 - Sam Rivera (Team Lead)',
    offer: '£3,800/mo',
    notes: 'Amazing team. Offer letter received 22/01/25.',
  },
  {
    no: '3',
    company: 'Revolut',
    roleTitle: 'Full Stack Developer',
    contract: 'Full Time',
    jobLink: 'https://revolut.com/careers',
    applicationDate: '07/01/25',
    response: 'Rejected',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Automated rejection after 5 days.',
  },
  {
    no: '4',
    company: 'Monzo',
    roleTitle: 'Junior Frontend Developer',
    contract: 'Full Time',
    jobLink: 'https://monzo.com/careers',
    applicationDate: '08/01/25',
    response: 'Phone Screen',
    interviewStage: 'Initial Call',
    interviewDetails: '14/01/25 11:30 - Priya Shah (Recruiter)',
    offer: '',
    notes: 'Went well. Technical round expected next week.',
  },
  {
    no: '5',
    company: 'Deliveroo',
    roleTitle: 'React Developer',
    contract: 'Contract',
    jobLink: '',
    applicationDate: '10/01/25',
    response: '',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Applied via LinkedIn.',
  },
  {
    no: '6',
    company: 'Canva',
    roleTitle: 'Product Engineer',
    contract: 'Full Time',
    jobLink: 'https://canva.com/careers',
    applicationDate: '12/01/25',
    response: 'Under Review',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Applied through referral from university contact.',
  },
  {
    no: '7',
    company: 'Palantir',
    roleTitle: 'Forward Deployed Engineer',
    contract: 'Full Time',
    jobLink: 'https://palantir.com/careers',
    applicationDate: '14/01/25',
    response: 'Technical Test',
    interviewStage: 'Online Assessment',
    interviewDetails: 'Deadline: 21/01/25',
    offer: '',
    notes: 'HackerRank — 90 min, 3 coding questions.',
  },
  {
    no: '8',
    company: 'Wise',
    roleTitle: 'Backend Engineer',
    contract: 'Full Time',
    jobLink: 'https://wise.com/careers',
    applicationDate: '15/01/25',
    response: 'Interview',
    interviewStage: '1st Round',
    interviewDetails: '22/01/25 15:00 - Chris Morgan (Tech Lead)',
    offer: '',
    notes: 'Focus on distributed systems and Go.',
  },
  {
    no: '9',
    company: 'Shopify',
    roleTitle: 'Developer Intern',
    contract: 'Intern',
    jobLink: 'https://shopify.com/careers',
    applicationDate: '17/01/25',
    response: '',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Applied to remote position.',
  },
  {
    no: '10',
    company: 'Linear',
    roleTitle: 'Software Engineer',
    contract: 'Full Time',
    jobLink: 'https://linear.app/careers',
    applicationDate: '18/01/25',
    response: 'Rejected',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Rejection cited lack of senior-level experience.',
  },
  {
    no: '11',
    company: 'Notion',
    roleTitle: 'Full Stack Engineer',
    contract: 'Full Time',
    jobLink: 'https://notion.so/careers',
    applicationDate: '20/01/25',
    response: '',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Submitted portfolio as part of application.',
  },
  {
    no: '12',
    company: 'Lemon Markets',
    roleTitle: 'Junior Developer',
    contract: 'Contract',
    jobLink: '',
    applicationDate: '22/01/25',
    response: 'Under Review',
    interviewStage: '',
    interviewDetails: '',
    offer: '',
    notes: 'Small fintech startup. Interesting product.',
  },
];
